"""empty message

Revision ID: 10549a16b5d0
Revises: 10c69d053f09
Create Date: 2014-03-20 03:18:10.037000

"""

# revision identifiers, used by Alembic.
revision = '10549a16b5d0'
down_revision = '10c69d053f09'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogPosts',
    sa.Column('postID', sa.Integer(), nullable=False),
    sa.Column('postTitle', sa.String(length=180), nullable=True),
    sa.Column('postBody', sa.Text(), nullable=True),
    sa.Column('postBody_html', sa.Text(), nullable=True),
    sa.Column('authorid', sa.Integer(), nullable=False),
    sa.Column('languageid', sa.Integer(), nullable=False),
    sa.Column('tranDate', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['authorid'], ['users.id'], ),
    sa.ForeignKeyConstraint(['languageid'], ['languages.languageid'], ),
    sa.PrimaryKeyConstraint('postID'),
    sa.UniqueConstraint('postTitle')
    )
    op.create_index('ix_blogPosts_tranDate', 'blogPosts', ['tranDate'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_blogPosts_tranDate', table_name='blogPosts')
    op.drop_table('blogPosts')
    ### end Alembic commands ###
