"""empty message

Revision ID: 1065ee4cfedc
Revises: 34b0ac3fe0c7
Create Date: 2014-03-20 05:07:53.320000

"""

# revision identifiers, used by Alembic.
revision = '1065ee4cfedc'
down_revision = '34b0ac3fe0c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_blogPosts_authorid', 'blogPosts', ['authorid'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_blogPosts_authorid', table_name='blogPosts')
    ### end Alembic commands ###
