"""empty message

Revision ID: 10c69d053f09
Revises: 318714ea11d
Create Date: 2014-03-20 02:18:38.766000

"""

# revision identifiers, used by Alembic.
revision = '10c69d053f09'
down_revision = '318714ea11d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
