"""empty message

Revision ID: 11e13456e67d
Revises: None
Create Date: 2014-03-19 23:02:46.935000

"""

# revision identifiers, used by Alembic.
revision = '11e13456e67d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('countryid', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=35), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('countryid')
    )
    op.create_index('ix_countries_country', 'countries', ['country'], unique=True)
    op.create_table('RelationTypes',
    sa.Column('relationTypeid', sa.Integer(), nullable=False),
    sa.Column('relationType', sa.String(length=35), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('relationTypeid'),
    sa.UniqueConstraint('relationType')
    )
    op.create_table('languages',
    sa.Column('languageid', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=35), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('languageid')
    )
    op.create_index('ix_languages_language', 'languages', ['language'], unique=True)
    op.create_table('states',
    sa.Column('stateid', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('stateid'),
    sa.UniqueConstraint('state')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_roles_default', 'roles', ['default'], unique=False)
    op.create_table('contactTypes',
    sa.Column('contactTypeid', sa.Integer(), nullable=False),
    sa.Column('contactType', sa.String(length=35), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('contactTypeid')
    )
    op.create_index('ix_contactTypes_contactType', 'contactTypes', ['contactType'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('avatar_hash', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_posts_timestamp', 'posts', ['timestamp'], unique=False)
    op.create_table('adminUsers',
    sa.Column('contactid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('addressline1', sa.String(length=60), nullable=True),
    sa.Column('addressline2', sa.String(length=60), nullable=True),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.Column('stateid', sa.Integer(), nullable=True),
    sa.Column('countryid', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=45), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('facebook', sa.String(length=20), nullable=True),
    sa.Column('twitter', sa.String(length=20), nullable=True),
    sa.Column('googleplus', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['countryid'], ['countries.countryid'], ),
    sa.ForeignKeyConstraint(['stateid'], ['states.stateid'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('contactid')
    )
    op.create_index('ix_adminUsers_timestamp', 'adminUsers', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_adminUsers_timestamp', table_name='adminUsers')
    op.drop_table('adminUsers')
    op.drop_index('ix_posts_timestamp', table_name='posts')
    op.drop_table('posts')
    op.drop_table('follows')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_contactTypes_contactType', table_name='contactTypes')
    op.drop_table('contactTypes')
    op.drop_index('ix_roles_default', table_name='roles')
    op.drop_table('roles')
    op.drop_table('states')
    op.drop_index('ix_languages_language', table_name='languages')
    op.drop_table('languages')
    op.drop_table('RelationTypes')
    op.drop_index('ix_countries_country', table_name='countries')
    op.drop_table('countries')
    ### end Alembic commands ###
