"""empty message

Revision ID: 1bab833a3cce
Revises: 1065ee4cfedc
Create Date: 2014-03-20 05:11:10.969000

"""

# revision identifiers, used by Alembic.
revision = '1bab833a3cce'
down_revision = '1065ee4cfedc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
