"""empty message

Revision ID: 25e50f3cb4aa
Revises: 10549a16b5d0
Create Date: 2014-03-20 03:49:23.289000

"""

# revision identifiers, used by Alembic.
revision = '25e50f3cb4aa'
down_revision = '10549a16b5d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
