"""empty message

Revision ID: 2bdf1e80a9be
Revises: 25e50f3cb4aa
Create Date: 2014-03-20 04:05:37.202000

"""

# revision identifiers, used by Alembic.
revision = '2bdf1e80a9be'
down_revision = '25e50f3cb4aa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
