"""empty message

Revision ID: 318714ea11d
Revises: 3a5f39108486
Create Date: 2014-03-20 02:15:42.803000

"""

# revision identifiers, used by Alembic.
revision = '318714ea11d'
down_revision = '3a5f39108486'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
