"""empty message

Revision ID: 34b0ac3fe0c7
Revises: 2bdf1e80a9be
Create Date: 2014-03-20 04:07:04.967000

"""

# revision identifiers, used by Alembic.
revision = '34b0ac3fe0c7'
down_revision = '2bdf1e80a9be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
