"""empty message

Revision ID: 3a5f39108486
Revises: 5498ec924281
Create Date: 2014-03-20 02:14:23.319000

"""

# revision identifiers, used by Alembic.
revision = '3a5f39108486'
down_revision = '5498ec924281'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
