"""empty message

Revision ID: 46653c4a2132
Revises: 1bab833a3cce
Create Date: 2014-03-20 05:14:20.237000

"""

# revision identifiers, used by Alembic.
revision = '46653c4a2132'
down_revision = '1bab833a3cce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('languages', 'language')
    op.drop_index('ix_languages_language', table_name='languages')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_languages_language', 'languages', ['language'], unique=1)
    op.add_column('languages', sa.Column('language', sa.VARCHAR(length=35), nullable=True))
    ### end Alembic commands ###
