"""empty message

Revision ID: 5498ec924281
Revises: 11e13456e67d
Create Date: 2014-03-19 23:20:55.875000

"""

# revision identifiers, used by Alembic.
revision = '5498ec924281'
down_revision = '11e13456e67d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('contactid', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=60), nullable=True),
    sa.Column('lastname', sa.String(length=60), nullable=True),
    sa.Column('relationTypeid', sa.Integer(), nullable=True),
    sa.Column('contactTypeid', sa.Integer(), nullable=True),
    sa.Column('preferredContact', sa.String(length=60), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['contactTypeid'], ['contactTypes.contactTypeid'], ),
    sa.ForeignKeyConstraint(['relationTypeid'], ['RelationTypes.relationTypeid'], ),
    sa.PrimaryKeyConstraint('contactid')
    )
    op.create_index('ix_contacts_timestamp', 'contacts', ['timestamp'], unique=False)
    op.add_column(u'adminUsers', sa.Column('preferredContactID', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'adminUsers', 'preferredContactID')
    op.drop_index('ix_contacts_timestamp', table_name='contacts')
    op.drop_table('contacts')
    ### end Alembic commands ###
